### ISSUE TITLE
fMRI searchlight

### ISSUE THREAD

**Issue by limbicode214** [rsagroup/rsatoolbox_matlab#39]
Hi

Have a look at fMRIsearchlight.m, line 172. 
fMRI searchlight will not work, because wrong function name. It should be:				
modelName = **underscoresToSpaces**(models(modelNumber).name)

After correcting this, I'll get another error message: 

Error in rsa.fmri.fMRISearchlight (line 203)
					warpDefFilename = replaceWildcards(fullfile(userOptions.structuralsPath, matchingFiles(1).name),
                    '[[subjectName]]', subject);

Error in Recipe_fMRI_searchlight (line 31)
rsa.fmri.fMRISearchlight(fullBrainVols, binaryMasks_nS, models, 'SPM', userOptions);

Please help, thanks

best, michael

**Comment by AgathaAnet** [comment]
Hi Michael,

Did you manage to overcome this second error? 
"Error in rsa.fmri.fMRISearchlight (line 203)
warpDefFilename = replaceWildcards(fullfile(userOptions.structuralsPath, matchingFiles(1).name),
'[[subjectName]]', subject);"

I've encountered the same...

Thank you

Regards, 
Agatha
