### ISSUE TITLE
Function `spm_vol` not found

### ISSUE THREAD

**Issue by Patli92** [rsagroup/rsatoolbox_matlab#43]
Hi,
I'm trying to feed in beta.nii files from my 1st-level GLM but got this error: Gathering scans.
Reading beta volumes for subject number 1 of 1: BUNC02Unrecognized function or variable 'spm_vol'.Error in rsa.fmri.fMRIDataPreparation (line 113) brainMatrix = spm_read_vols(spm_vol(readPath));
The toolbox does not have 'spm_vol' function, how can I solve this problem? Thanks!
-Ran

**Comment by Remi-Gau** [comment]
Not a regular user of the RSA toolbox but this looks like an SPM dependency (`spm_vol` and `spm_read_vols`) are 2 of the main function that spm uses to read images headers and content.

Given that the RSA toolbox does not have to have them in its SPM folder: https://github.com/rsagroup/rsatoolbox/tree/develop/%2Brsa/%2Bspm

I suspect the workaround is to install spm (https://www.fil.ion.ucl.ac.uk/spm/software/) and make sure it is added to the path of matlab.

will let any of the RSA toolbox people confirm this. :wink:

**Comment by caiw** [comment]
Yes, that's right. These functions come from SPM.
