### ISSUE TITLE
Query userOptions for LSS folder structure

### ISSUE THREAD

**Issue by LisaWirz** [rsagroup/rsatoolbox_matlab#48]
Hi
I have a question regarding the definition of the userOptions.betaPath. There is a placeholder for the subject and the betaIdentifier. If I am not mistaken this assumes that there is 1 GLM, in which each trial is modeled separately (LSA). However, based on Mumford's work I wanted to use the LSS approach, meaning that for each subject I now have 1 GLM per trial. For each GLM, 1trial of interest is modelled as 1 regressor, all other trials collapsed into 1 regressor. This means I have 1 folder per trial, but there is no wildcard for such a structure when defining the path. Is there any way to adjust this or any idea for a workaround? Thanks a lot in advance!
Cheers
Lisa

**Comment by LisaWirz** [comment]
I was a bit too hasty with posting this problem. I could easily just change the betaCorrespondence filename by adding part of the folder path for which there is no wildcard in the userOptions.betaPath

**Comment by caiw** [comment]
Glad you found a solution!
